runtime: python
env: flex

#entrypoint: gunicorn -b :$PORT -k gevent robotinomanager:app
entrypoint: gunicorn -b :$PORT -k flask_sockets.worker robotinomanager:app

runtime_config:
  python_version: 3
  
manual_scaling:
  instances: 1

#network:
#  session_affinity: true